export const CATEGORY_TABLE = {
  1: ['Spring', 'Beer'],
  2: ['Spring', 'Wine'],
  3: ['Spring', 'Spirits'],
  4: ['Spring', 'Soju'],
  5: ['Spring', 'Sake'],
  6: ['Spring', 'Makgeolli'],
  7: ['Summer', 'Beer'],
  8: ['Summer', 'Wine'],
  9: ['Summer', 'Spirits'],
  10: ['Summer', 'Soju'],
  11: ['Summer', 'Sake'],
  12: ['Summer', 'Makgeolli'],
  13: ['Autumn', 'Beer'],
  14: ['Autumn', 'Wine'],
  15: ['Autumn', 'Spirits'],
  16: ['Autumn', 'Soju'],
  17: ['Autumn', 'Sake'],
  18: ['Autumn', 'Makgeolli'],
  19: ['Winter', 'Beer'],
  20: ['Winter', 'Wine'],
  21: ['Winter', 'Spirits'],
  22: ['Winter', 'Soju'],
  23: ['Winter', 'Sake'],
  24: ['Winter', 'Makgeolli'],
};
